<?php
/**
 * @file
 * Cats, cats everywhere...
 */

/**
 * Implements hook_menu().
 */
function cats_menu() {
  return [
    'furry-love' => [
      'page callback' => '_cats_page_callback',
      'access callback' => '_cats_page_access',
    ],
  ];
}


/**
 * Implements hook_theme().
 */
function cats_theme() {
  return [
    'cat_image' => [
      'variables' => ['url' => NULL],
      'template' => 'cat_image',
    ],
  ];
}

/**
 * Implementation of page callback for /furry-love.
 */
function _cats_page_callback() {
  return [
    '#markup' => theme('cat_image', ['url' => 'http://thecatapi.com/api/images/get?format=src&type=gif']),
  ];
}

/**
 * Implementation of access callback for /furry-love
 */
function _cats_page_access() {
  return TRUE;
}


/**
 * Implements hook_block_info().
 */
function cats_block_info() {
  return [
    'cats' => [
      'info' => t('Block with random cat.'),
    ]
  ];
}

/**
 * Implements hook_block_view().
 */
function cats_block_view($delta) {
  switch ($delta) {
    case 'cats':
      return [
        'content' => '<img src="http://thecatapi.com/api/images/get?format=src&type=gif" />',
        'subject' => t('Cats'),
      ];
  }
}


/**
 * Implements hook_preprocess().
 */
function cats_preprocess(&$variables, $hook) {
  if ($hook == 'cat_image') {
    drupal_add_js(
      drupal_get_path('module', 'cats') . '/cats.js'
    );
  };

  return $variables;
}
